name: Lint

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm

      - run: npm install
      - run: npm run lint
